# Generated by Django 5.0.7 on 2024-07-25 08:37

from django.db import migrations
from django.contrib.auth.hashers import make_password

def seed_data(apps, schema_editor):
    """
    Seeds the database with initial users and wiki pages.
    """
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('wiki', 'UserProfile')
    WikiPage = apps.get_model('wiki', 'WikiPage')

    # Create an admin user
    admin_user, admin_created = User.objects.get_or_create(
        username='admin',
        defaults={
            'password': make_password('admin'),
            'is_superuser': True,
            'is_staff': True,
            'first_name': 'Admin',
            'last_name': 'User',
            'email': 'admin@example.com'
        }
    )
    if admin_created:
        UserProfile.objects.create(user=admin_user, bio='I am the administrator.', signature='Admin')

    # Create a regular editor user
    editor_user, editor_created = User.objects.get_or_create(
        username='editor',
        defaults={
            'password': make_password('password123'),
            'is_staff': False,
            'is_superuser': False,
            'first_name': 'Regular',
            'last_name': 'Editor',
            'email': 'editor@example.com'
        }
    )
    if editor_created:
        UserProfile.objects.create(user=editor_user, bio='I am a regular editor.', signature='Editor')

    # Create sample wiki pages
    pages_to_create = [
        {
            'title': 'Welcome to Your New Wiki',
            'content': (
                "## Welcome!\n\n"
                "This is your first page in **CollabXSS Wiki**. "
                "Feel free to edit this page or create a new one to get started.\n\n"
                "You can use Markdown to format your content."
            ),
            'author': admin_user,
            'category': 'General'
        },
        {
            'title': 'Markdown Formatting Guide',
            'content': (
                "## Basic Formatting\n\n"
                "Here are some quick tips for using Markdown:\n\n"
                "- **Bold Text**: `**your text**`\n"
                "- *Italic Text*: `*your text*`\n"
                "- Strikethrough: `~~your text~~`\n\n"
                "### Headers\n\n"
                "Use hash symbols for headers:\n"
                "`# H1`\n`## H2`\n`### H3`\n\n"
                "### Lists\n\n"
                "**Ordered List**\n"
                "1. First item\n"
                "2. Second item\n\n"
                "**Unordered List**\n"
                "- Bullet point\n"
                "- Another bullet point\n\n"
                "For more details, check out a comprehensive Markdown cheat sheet online."
            ),
            'author': editor_user,
            'category': 'How-To'
        },
        {
            'title': 'About This Project',
            'content': (
                "This project is a Django-based wiki built to demonstrate collaborative editing features. "
                "It is also used as a learning platform to understand and identify common web security vulnerabilities like Cross-Site Scripting (XSS)."
            ),
            'author': admin_user,
            'category': 'Project Info'
        }
    ]

    for page_data in pages_to_create:
        WikiPage.objects.get_or_create(
            title=page_data['title'],
            defaults=page_data
        )

def unseed_data(apps, schema_editor):
    """
    Removes the initial seeded data.
    """
    User = apps.get_model('auth', 'User')
    WikiPage = apps.get_model('wiki', 'WikiPage')

    # Delete users created by the seeder
    User.objects.filter(username__in=['admin', 'editor']).delete()

    # Delete pages created by the seeder
    page_titles = [
        'Welcome to Your New Wiki',
        'Markdown Formatting Guide',
        'About This Project'
    ]
    WikiPage.objects.filter(title__in=page_titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_data, unseed_data),
    ]
